FROM alpine:3

LABEL author="Putri Qonita Arif"
LABEL company="Sister Tugas Praktikum Dockerfile" website="https://www.itk.ac.id/"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"