FROM golang:1.18-alpine

RUN mkdir /app

RUN addgroup -S sistergroup && adduser -S sisteruser -G sistergroup
RUN chown -R sisteruser:sistergroup /app
USER sisteruser

COPY main.go /app

EXPOSE 8080
CMD go run /app/main.go